// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import DisplayButtonsController from "./display_buttons_controller"
application.register("display-buttons", DisplayButtonsController)

import EditCommentController from "./edit_comment_controller"
application.register("edit-comment", EditCommentController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
